### ISSUE TITLE
Add cog with user menu no longer works.

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/bootstrap5_lite#35]
Following the recent updates to support bootstrap 5.3.1 CDN and the option to use bundled bootstrap files, the seeting for Navbar to "Add cog with user-menu". No longer works. It does not work when the CDN is set to 5.0.1 or with 5.3.1 version. This was previously working.
![bootstrap-5 0 1-add-cog-user-menu](https://github.com/backdrop-contrib/bootstrap5_lite/assets/6208775/16cbf2e8-8c27-40bd-a22d-e09d5e561913)

**Comment by bugfolder** [comment]
Ah, this is because the cog is provided by FontAwesome, which has been unbundled and is now a separate module.

If you install [FontAwesome](https://backdropcms.org/project/font_awesome), the cog will reappear.

For this theme, we should note in that checkbox setting that FA is required for this. Maybe for a future feature, allow users to enter their own preferred icon HTML. (The current icon HTML is `<i class="fa fa-cog"></i>`.)

**Comment by robertgarrigos** [comment]
This PR does work with bootstrap 5.0.1. and 5.1.3, but it is NOT working when bootstrap version is set to 5.3.1, either CDN or bundled. With these versions, gear DOES appear but clicking on it triggers a js error:

```
dropdown.js:241 Uncaught TypeError: i.createPopper is not a function
    at fe._createPopper (dropdown.js:241:27)
    at fe.show (dropdown.js:139:10)
    at fe.toggle (dropdown.js:121:49)
    at HTMLDivElement.<anonymous> (dropdown.js:446:38)
    at HTMLDocument.s (event-handler.js:118:19)
```
I wonder if this is a Bootstrap problem and not of this PR.

**Comment by robertgarrigos** [comment]
I've found this issue in stackoverflow which might give us an answer: https://stackoverflow.com/questions/68750341/bootstrap-5-uncaught-typeerror-popper-namespace-createpopper-is-not-a-functi

**Comment by robertgarrigos** [comment]
Found the solution: changing the lines (two places) where template.php loads `bootstrap.min.js` by `bootstrap.bundle.min.js`. Then this PR works for 5.3.1, also for 5.3.2 and 5.3.3.

**Comment by docwilmot** [comment]
Since we've got SVG in core now, can we just use a core icon instead of relying on a whole module?

**Comment by robertgarrigos** [comment]
mmm sorry, just reading your comment after committing the pr. Your proposition sounds reasonable, of course. Giving it is already committed, should we open a new issue?
